<a href="https://colab.research.google.com/github/Hirahir/ML_Journer_00/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# we are doing tensorflow fundamentals

More specifically, we're going to cover:
• Introduction to tensors
• Getting information from tensors
• Manipulating tensors
• Tensors & NumPy
• Using @tf.function (a way to speed up your regular Python functions)
• Using GPUs with TensorFlow (or TPUs)
• Exercises to try for yourself!






In [ ]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [ ]:
# create tensor with tf.constant()
scalar =  tf.constant( 1001)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1001>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# creating a vector
vector = tf.constant([100,101,1])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([100, 101,   1], dtype=int32)>

In [ ]:
# checking the dimentions of vector
vector.ndim

1

In [ ]:
# creating a matrix (has more dimensions then 1 in any matrix)
matrix=tf.constant([[1,2],[2,1]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 1]], dtype=int32)>

In [ ]:
# creating another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]],
                            dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# dimensions of another_matrix
another_matrix.ndim


2

In [ ]:
#lets create a tensor
tensor =tf.constant([[[1,2,3,],
                      [4,5,6,]],
                      [[7,8,9,],
                      [10,11,12,]],
                      [[13,14,15,],
                       [16,17,18,]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:
• Scalar: a single number
• Vector: a number with direction (e.g. wind speed and direction)
• Matrix: a 2-dimensional array of numbers
• Tensor: an -dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is vector)

Creating tensors with tf.variables

In [ ]:
changeable_tensor = tf.Variable ([10,7])
unchangeable_tensor= tf.constant ([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

# lets change the element of changeable tensor(.assign)



In [ ]:
changeable_tensor[1].assign(999999)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([    10, 999999], dtype=int32)>

In [ ]:
# creating random tensors
import tensorflow as tf

random_01 = tf.random.Generator.from_seed(0)
random_01 = random_01.normal(shape=(3,3),dtype=tf.float16)

random_02 = tf.random.Generator.from_seed(0)
random_02 = random_02.normal(shape=(3,3),dtype=tf.float16)

random_01,random_02,random_01 == random_02 ,random_02 == random_01

(<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
 array([[-1.3545 ,  0.7046 ,  0.03665],
        [ 0.869  ,  0.4385 , -0.534  ],
        [-0.0771 ,  1.565  , -0.10126]], dtype=float16)>,
 <tf.Tensor: shape=(3, 3), dtype=float16, numpy=
 array([[-1.3545 ,  0.7046 ,  0.03665],
        [ 0.869  ,  0.4385 , -0.534  ],
        [-0.0771 ,  1.565  , -0.10126]], dtype=float16)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [ ]:
# Shuffle a tenor (valuable for when you want to shuffle your data so the inherent
non_shuffle = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
## Shuffle our non_shuffled tensor
tf.random.shuffle(non_shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [ ]:
nonshuffle_1 = tf.constant ([[[1,2],
                           [3,4]],
                           [[4,5],
                           [6,7]]])
# Shuffle the nonshuffle_1 tensor
#tf.random.set_seed()
tf.random.shuffle(nonshuffle_1)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[4, 5],
        [6, 7]],

       [[1, 2],
        [3, 4]]], dtype=int32)>

In [ ]:
tf.random.shuffle(random_01,seed=32)

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[-0.0771 ,  1.565  , -0.10126],
       [-1.3545 ,  0.7046 ,  0.03665],
       [ 0.869  ,  0.4385 , -0.534  ]], dtype=float16)>

In [ ]:
tensor =tf.constant([[[1,2,3,],
                      [4,5,6,]],
                      [[7,8,9,],
                      [10,11,12,]],
                      [[13,14,15,],
                       [16,17,18,]]])
tensor
tf.random.shuffle(tensor)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
#It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation leve random seed:
#Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."



#Other ways to make tensors

In [ ]:
#creating the tensors with all ones
import tensorflow as tf
tf.fill((3,4), 9)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]], dtype=int32)>

In [ ]:
## turn NumPy Arrays into Tensors
# the main differences between NumPy Arrays and Tensorflow Tensors is. that tensors can be run in GPU(much faster for numerical computing)


In [ ]:
# You can also turn NumPy Arrays into Tensors
import tensorflow as tf
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)# creating a NumPy array between 1 to 25
numpy_A
# X = tf.constant (some matrix) # capital for matrix or tensor
# y = tf.constant (vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
#Changing NumPy array into tensors
Numpy_to_tensors =tf.constant(numpy_A,shape=(1,2,3,4))#this is a tensor with more then one dimensions
Numpy_to_tensors1 =tf.constant(numpy_A)# this is a vector (only one dimensions)
Numpy_to_tensors,Numpy_to_tensors1

(<tf.Tensor: shape=(1, 2, 3, 4), dtype=int32, numpy=
 array([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],
 
         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
# creating 4 rank tensors(4 dimensons tensor)
import tensorflow as tf
dim4_rank_tensor = tf.ones(shape=(5,3,4,5))
dim4_rank_tensor
#dim4_rank_tensor.ndim


<tf.Tensor: shape=(5, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]

In [ ]:
##axis of tensor
dim4_rank_tensor[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
##checking the shape,dimensons and size of the tensor
dim4_rank_tensor.shape,dim4_rank_tensor.ndim,tf.size(dim4_rank_tensor)

(TensorShape([5, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=300>)

In [ ]:
## To get various attribusts from our tenosr
print("Datatype of every element:",dim4_rank_tensor.dtype)
print("Number of dimensons(ranks):",dim4_rank_tensor.ndim)
print("shape of tensor:",dim4_rank_tensor.shape)
print("All the elimints for 0 Axis:",dim4_rank_tensor.shape[0])
print("all the elements from last Axis:",dim4_rank_tensor.shape[-1])
print("Total no of elements in our tensor:",tf.size(dim4_rank_tensor))
print("Total no of elements in our tensor:",tf.size(dim4_rank_tensor).numpy())


Datatype of every element: <dtype: 'float32'>
Number of dimensons(ranks): 4
shape of tensor: (5, 3, 4, 5)
All the elimints for 0 Axis: 5
all the elements from last Axis: 5
Total no of elements in our tensor: tf.Tensor(300, shape=(), dtype=int32)
Total no of elements in our tensor: 300


###Indexing And Expanding Tensors

In [ ]:
##Getting first 2 elements from each dimensions(dim4_rank_tensor):means slicing the list
dim4_rank_tensor[:2 ,:2, :2 ,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [ ]:
##get each emlement except last from all the dims
dim4_rank_tensor[0:-1,0:-1,0:-1,0:-1,]

<tf.Tensor: shape=(4, 2, 3, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
## Get the First elements from the all dims expect for the n dimensons (n can be any dimensons)
dim4_rank_tensor[:1,:1,:1,:]


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1., 1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
#Creating a rank 2 tensor
rank_2_tensor=tf.constant([[11,22],[33,44]])
rank_2_tensor.shape

TensorShape([2, 2])

In [ ]:
## getting the last item from row of our rank 2 tensor
rank_2_tensor[:1,-1]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([22], dtype=int32)>

In [ ]:
## how to add new dim to our rank 2 tensor(what is new axis)new dimenson in our old tensor without canging the values just adding a dimenson
rank_3_tensor=rank_2_tensor[...,tf.newaxis] #... means all axis before
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[11],
        [22]],

       [[33],
        [44]]], dtype=int32)>

In [ ]:
##alternative for tf.newaxis=tf.expand_dim
tf.expand_dims(rank_2_tensor,axis=0)


<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[11, 22],
        [33, 44]]], dtype=int32)>

In [ ]:
### Manipulating tensors (tensor operations)
## basic operators(+,-,*,/)
import tensorflow as tf

tensor= tf.constant([[10,11],[12,13]])
tensor[1]+10


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([22, 23], dtype=int32)>

In [ ]:


tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 11],
       [12, 13]], dtype=int32)>

In [ ]:
##MULTIPLICATION
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 110],
       [120, 130]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 11],
       [12, 13]], dtype=int32)>

In [ ]:
## we can use the tensor flow function for operations
tf.math.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 110],
       [120, 130]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 11],
       [12, 13]], dtype=int32)>

In [ ]:
 ###tensor multiplication
 print(tensor)

tf.Tensor(
[[10 11]
 [12 13]], shape=(2, 2), dtype=int32)


In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[232, 253],
       [276, 301]], dtype=int32)>

In [ ]:
# Matrix mutliplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[232, 253],
       [276, 301]], dtype=int32)>

In [ ]:
#L Resource: Info and exmaple of matrix multiplication:  https://www.mathsisfun.com/algebra/matrix-multiplying.html
#There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:
#1. The inner dimensions must match
#2. The resulting matrix has the shape of the outer  dimensions



In [ ]:
#lets multiply the (3*3)and 2*3 matrix (which actually cannot be multiplied)
matrix_a=tf.constant([[1,2],
                      [2,4],
                      [5,6]])
matrix_b=tf.constant([[1,2],
                     [3,4],
                     [5,6]])
matrix_a , matrix_b

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)

In [ ]:
tf.matmul(matrix_a,matrix_b)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [ ]:
## we cant multiply the upper matrix so reshape it
tf.reshape(matrix_b,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
matrix_a.shape,matrix_b.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [ ]:
## lets multiplly matrix a and reshaped matrix b
tf.matmul(matrix_a,tf.reshape(matrix_b,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [18, 24, 30],
       [29, 40, 51]], dtype=int32)>

In [ ]:
## lets change the shape of matrix_a
tf.reshape(matrix_a,shape=(2,3))@matrix_b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 22],
       [49, 64]], dtype=int32)>

In [ ]:
### Transpose and Reshape
matrix_a,tf.transpose(matrix_a),tf.reshape(matrix_a,shape=(2,3))##Transpose changes the whole row to column and colume to row
                                                               ##but tf.reshape just changes the shape of tensor without playing with the elements within

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 2],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
###The Dot Produce
#matrix multiplication is also referred to as the dot produce
#you can perform matrix multiplication using.
 #1.'tf.matmul()'
 #2.'tf.tensordot()'
 #3.@


In [ ]:
##Performing the dot produce on X and Y (if the axes doesn't allign X or Y should be transposed)Not reshaped
import tensorflow as tf
tf.tensordot(matrix_a,tf.transpose(matrix_b),axes=1)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [10, 22, 34],
       [17, 39, 61]], dtype=int32)>

In [ ]:
matrix_a,matrix_b

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)

In [ ]:
## changing the data types of a tensor


The default data type of a tensor is int32 but i depends how the tensor is created

In [ ]:
##Lets create a tensor with default data type float 32
A = tf.constant([1.5,1.9])
A

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 1.9], dtype=float32)>

In [ ]:
B=tf.constant([12,13])
B

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 13], dtype=int32)>

In [ ]:
## lets change the precision of the datatype(float32 to float 16)
A=tf.cast(A,dtype=tf.float16)
A

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.5, 1.9], dtype=float16)>

In [ ]:
B=tf.cast(B,dtype=tf.int16)
B

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([12, 13], dtype=int16)>

In [ ]:
A

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.5, 1.9], dtype=float16)>